import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google'
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/app/SessionProvider";
import { authOptions } from "@/lib/authOption";
const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Kaban task manager",
  description: "Generated by Trần Thành Danh",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <SessionProvider session={session} >
      <html lang="en">
        <body className={`${jakarta.className} antialiased tracking-wider`}>
          {children}
        </body>
      </html>
    </SessionProvider>

  );
}
